### ISSUE TITLE
последний шаг обучения отображается рвано.

### ISSUE THREAD

**Issue by SergeiIm** [akdasa-studios/shlokas#262]
описание ошибки: при воспроизведении последнего шага обучения линия прогресса отображается прерывисто и не до конца (возможно высокая нагрузка на анимацию с конфети, при этом отсчет времени отображения сообщения не связан с прогресс баром.)
ожидается: плавная анимация.
шаги воспроизведения: обучение.

примечание: отсутствие возможности воспроизвести обучение повторно.

**Comment by akdasa** [comment]
It depends on device performance.
