### ISSUE TITLE
Аудио есть, круга нет.

### ISSUE THREAD

**Issue by SergeiIm** [akdasa-studios/shlokas#264]
Ошибка: если добавить карточку без интернета, а потом включить и синхронизировать то звук не появляется хотя и есть в библиотеке.
ожидается: звук подтягивается к карточке.
шаги воспроизведения: ....

**Comment by akdasa** [comment]
Причина: не очищался кэш загруженный шлок. Поэтому при повторном запросе шлоки, возвращалась старая версия, а не та что была загружена (обновлена) из интернета.
