### ISSUE TITLE
Don't allow the user to swipe up all cards unless asked to do so

### ISSUE THREAD

**Issue by SergeiIm** [akdasa-studios/shlokas#286]
Users can break tutorial script and get stuck

## Expected Behavior
The user cannot swipe the card up if it is not expected by the tutorial script

## Current Behavior
[Tell us what happens instead of the expected behavior](https://github.com/akdasa-studios/shlokas/assets/128727366/1dc2b40f-a4b9-4427-acbf-5a63535f0e77)

## Context (Environment)
Any device

**Comment by akdasa** [comment]
This we should fix before 1.2.4
